title: J Koesnoom
theme: just-the-docs

url: https://aloaiyo.github.io

aux_links:
  Template Repository: https://github.com/aloaiyo/aloaiyo.github.io

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-X6HK71255Z
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

google_site_verification: 

plugins:
  - jekyll-sitemap